version: "3"
services:
  yellow-taxi-data:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile

    env_file:
      - secrets
    ports:
      - 9000:9000
    command: gunicorn -c python:yellow_taxi_data.gunicorn_config --worker-tmp-dir /tmp --log-file - -k uvicorn.workers.UvicornWorker -b 0.0.0.0:9000  --reload 'yellow_taxi_data.main:app'
